# Generated by Django 5.0.1 on 2024-01-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(default="Default.png", upload_to="Product"),
        ),
    ]
